### ISSUE TITLE
Getting error SV - measure ID 128 is not allowed to be submitted to the mips program

### ISSUE THREAD

**Issue by NeetaRamani** [CMSgov/qpp-conversion-tool#1454] opened 2024-09-05 11:00 UTC
When trying to convert the file on swagger (https://preview.qpp.cms.gov/api/submissions/public/docs/#/Conversion/ConversionController_converterPlaceholder), it is giving error - 
SV - measure ID 128 is not allowed to be submitted to the mips program.  Please remove the invalid measure from the measurement set.
attached the actual file with response from swagger for reference.

Can you please help here what is going wrong or this measure is not supposed to be submitted?

**Comment by sivaksb** [comment] 2024-09-05 13:37
@NeetaRamani Let me take a look.  I need to cross check with [2024 Measures Data](https://github.com/CMSgov/qpp-measures-data/blob/develop/measures/2024/measures-data.json#L4665)

**Comment by sivaksb** [comment] 2024-09-05 14:02
@NeetaRamani I have confirmed that the measure 128 is not reportable to MIPS for PY24.  It is an MVP only measure.  Please check the link in the above comment that lists the allowed programs for this measure.

**Comment by NeetaRamani** [comment] 2024-09-06 05:11
Thank you @sivaksb for you prompt response here. Got that we need to submit only MIPS related measure, however in the above link I see that 128 measure is present.
![image](https://github.com/user-attachments/assets/fc1eca41-ec5e-431c-9c5f-6d4512946360)

**Comment by sivaksb** [comment] 2024-09-06 16:22
@NeetaRamani Yes, all the PY24 eligible measures will be listed in there.  However you need to check the allowed programs field.  If `mips` is listed there, only then it can be submitted for MIPS.  Hope this helps.
![image](https://github.com/user-attachments/assets/15d8c43f-a5b9-4b3f-bacd-2fe1a62f97a0)

**Comment by NeetaRamani** [comment] 2024-09-09 09:42
Yes, this helped. Thank you very much!

I just had one more question, when doing preview score on the same swagger with valid cert ID, getting following error - 

{"errors":[{"sourceIdentifier":null,"type":"ValidationError","message":"invalid submission object","details":[{"errorCode":null,"message":"SV - must be a 15 digit alphanumeric of format XX15CXXXXXXXXXX for performanceYear 2024","value":null,"type":null,"location":{"location":null,"path":"/*[local-name() = 'ClinicalDocument' and namespace-uri() = 'urn:hl7-org:v3']","line":null,"column":null}}]}]}

Attached is the xml file for reference. Can you please suggest what is going wrong here?
[QRDA_III.zip](https://github.com/user-attachments/files/16928653/QRDA_III.zip)

**Comment by sivaksb** [comment] 2024-09-09 13:47
Could you please attach just the xml file, instead of zip file.  I will take a look once I have that document.  For now, just looking at the error, it looks like you have an invalid cehrt id (Certified EHR Technology id).  It should be in the above mentioned format.  What value do you have for the below root id?

`<id root="2.16.840.1.113883.3.2074.1" extension="XX15CXXXXXXXXXX"/>`

**Comment by NeetaRamani** [comment] 2024-09-10 04:09
Unfortunately, it is not allowing to attach the xml file so I zipped the file and uploaded. The value in the extension is - 
<id root="2.16.840.1.113883.3.2074.1" extension="0015ETG536GVT1R" assigningAuthorityName="ONC"/>

**Comment by sivaksb** [comment] 2024-09-10 14:42
Thats the issue.  The value in the extension is invalid and that's why its throwing that error.  You can input the same extension value from my above comment and try.  Because the issue is on the input, I will be closing this issue for now.  If you face any issue related to the tool or bug in the code, please open another one.  Thanks!

**Closed by sivaksb** 2024-09-10 14:42 UTC
