### ISSUE TITLE
CPC+: DateTimeParseException in the latest version but success in an earlier version

### ISSUE THREAD

**Issue by nathandonato** [CMSgov/qpp-conversion-tool#625] opened 2018-02-21 17:05 UTC
### Information
- OS & version:
-- macOS Sierra
-- Whatever the production QPP utility's OS is
- Java version:
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
- Docker version:

```
Docker version 17.12.0-ce, build c97c6d6
```

### Expected behavior
A successful conversion. See attached JSON:
[success.json.txt](https://github.com/CMSgov/qpp-conversion-tool/files/1744856/success.json.txt)

### Actual behavior
This results in a `DateTimeParseException`. See attached log:
[error.log](https://github.com/CMSgov/qpp-conversion-tool/files/1744935/error.log)

### Steps to reproduce
1. Download this file (remove .txt extension added for github):
[CPC_PLUS_FAILURE.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/1744974/CPC_PLUS_FAILURE.xml.txt)

1. Checkout the commit `c18f8f976` (latest version at the time of writing this issue)
2. Run qpp conversion tool
3. POST the file downloaded in step 1, with headers specified in the documentation
4. See that the response is `CT-unexpected exception occurred during conversion`
5. See that the qpp conversion tool logged an exception

### Other details
* This is also happening for a production qpp submission (same file but with real info)

* **Expected behavior** can be achieved if you repeat the above steps but in step 2 checkout the commit `66510dba` instead

* The file works if you change the `intendedRecipient` extension to `MIPS_GROUP` (line 103 of the document), which suggests this error is unique to the CPC+ code

**Comment by aaroalan** [comment] 2018-02-21 17:32
Looks like the issue is a missing env var `CPC_END_DATE`, `CpcClinicalDocumentValidator.java` has this line `LocalDate.parse(EnvironmentHelper.getOrDefault(END_DATE_VARIABLE, NEVER_ENDING))` but looks like it's returning an empty string instead null so it tries to parse `''` and not `NEVER_ENDING` value.

You can fix it **locally** if you se the env var in the `docker-compose.test.yaml` 
```xml
...
environment:
  - CPC_END_DATE=3000-01-01
...
```

**Comment by aaroalan** [comment] 2018-02-21 17:38
Update: Don't need to update the docker-compose file `.env` file has `CPC_END_DATE=` so that's why var is `''`

**Comment by sfradkin** [comment] 2018-02-21 17:48
We'll double check the documentation to ensure that this is called out in the docs as an env var to modify.  We can also just provide a default value in the `.env` file.

**Comment by aaroalan** [comment] 2018-02-21 17:50
Maybe the `EnvironmentHelper` should validate that value is not null and is not a empty string, What do you think?

**Comment by halprin** [comment] 2018-02-21 17:55
Nice catch!  And yeah, I think that changing `EnvironmentHelper` to also return the default on an empty string is appropriate, @aaroalan.

**Comment by sfradkin** [comment] 2018-02-21 19:25
@aaroalan @nathandonato: We have added this issue to our backlog and it will be prioritized today.  We will let you know via this issue when changes have been made.

**Comment by nathandonato** [comment] 2018-02-21 19:43
Thanks @sfradkin! I'm sure you're aware and will factor this into the priority, but it's probably worth overstating: CPC+ submissions are due in one week (2018-02-28).

**Comment by sfradkin** [comment] 2018-02-21 20:43
@nathandonato Yes we are aware of this.  However, since there is a stated solution in this thread as to how to set the environment variable, and there is a publicly available sandbox at https://qpp.cms.gov/developers/conversion-tool-sandbox that uses our production code, that lowers the priority of this a bit.

**Comment by nathandonato** [comment] 2018-02-21 21:33
That makes sense, thanks for the follow up.  But we are getting this error when doing QRDA III XML submissions _(we assume this is the error; the response is error code 3, and this is the actual exception we get locally for the same file)_.

So we can use the environment variable solution in our testing, but is there any chance you guys will set the environment variable in production?

**Comment by sfradkin** [comment] 2018-02-21 22:06
Ah, sorry.  I missed the part that you tried this as a real submission and got the same error.  I can confirm that I am seeing that error with your file.  We'll take a look at this to see what's going on as it's unrelated to the CPC_END_DATE.

**Comment by nathandonato** [comment] 2018-02-21 22:09
Sorry, that's my fault. I should have been more clear. Thanks for looking into it.

**Comment by sfradkin** [comment] 2018-02-21 22:26
@nathandonato Looking at this further it appears that you have a missing code in one of your supplemental data elements.  We are already working on a fix for this situation so that it correctly outputs an error with the xpath rather than returning an "unexpected error".  It's tough to eyeball the QRDA document to find the missing code, but that's where you can look.

We're going to work on getting this fix out as a hotfix to production by the end of the day tomorrow.

**Comment by nathandonato** [comment] 2018-02-22 15:06
@sfradkin We believe we found the issue. Thanks for pointing us in the right direction!

**Comment by sfradkin** [comment] 2018-02-23 15:33
@nathandonato We have deployed a new version of the converter to production.  Please try it out and see if that gets your file converted and submitted.

**Comment by sfradkin** [comment] 2018-03-06 19:55
With no response for over a week, I'm going to go ahead and close this issue as fixed.

**Closed by sfradkin** 2018-03-06 19:55 UTC
Labels: bug, enhancement
