### ISSUE TITLE
Segment error output with no line number indicated when segment is present

### ISSUE THREAD

**Issue by chacliff** [CMSgov/qpp-conversion-tool#651] opened 2018-03-14 21:50 UTC
### Information
- OS & version:
Windows 10
- Java version: *(Run `$ java -version`.)*
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- Docker version if using: *(Run `$ docker -v`.)* N/A

### Expected behavior
Submitted document via the command line arguement. "convert.bat <fileName>. 
Expecting each of the measure entries to not produce any errors. Basically Recieved this errors from a physician that tried to submit one of our documents.  They are exactly to spec and we are a certified Vendor. I can perhaps attach the file after removing some information. for now Will post a snapshot of one of the measure entries. I expected to receive more than just a general segment location. My segment that it is describing is present. Line numbers of the file submitted might help identifying error locations during validation. 

### Actual behavior
I recieved the following error. 
`{
      "errorCode" : 52,
      "message" : "CT - Measure data must have exactly one Aggregate Count.",
      "path" : "/*[local-name() = 'ClinicalDocument' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'structuredBody' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3'][1]/*[local-name() = 'section' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'entry' and namespace-uri() = 'urn:hl7-org:v3'][2]/*[local-name() = 'organizer' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3'][1]/*[local-name() = 'observation' and namespace-uri() = 'urn:hl7-org:v3']"
    }`

### Steps to reproduce
1. run convert.bat against file containing QRDA3 document

### Other details
Below is one of the segments that it is complaining about that it seems to not be detecting. 
For the purpose of this post i do not find it necessary to post anymore info that the below segment and its parent sections segments. 

The below xml will produce the error i am experiencing. I recognize it is not a fully fleshed QRDA III document, but it will produce the issue that i am looking to resolve at this moment. 

`<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="qrda.xsl"?>
<ClinicalDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:hl7-org:v3" xmlns:voc="urn:hl7-org:v3/voc">
	
	
	<realmCode code="US" />
	
	<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040" />
	
	<templateId root="2.16.840.1.113883.10.20.27.1.1" extension="2017-06-01" />
	
	<templateId root="2.16.840.1.113883.10.20.27.1.2" extension="2017-07-01" />
	
	<id root="7B728D24-AF10-4046-9D0B-4A56DF799905" />
	
	<code code="55184-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Quality Reporting Document Architecture Calculated Summary Report" />
	
	<title>Eligible Clinicians (EC) Meaningful Use Group Sample QRDA-III (Informative)</title>
	
	<effectiveTime value="20180312080030" />
	
	<confidentialityCode codeSystem="2.16.840.1.113883.5.25" code="N" />
	
	<languageCode code="en" />
	<setId root="7B728D24-AF10-4046-9D0B-4A56DF799905" />
	<versionNumber value="1" />
	
	
	<component>
		<structuredBody>
			
			<component>
				<section>
					
					<templateId root="2.16.840.1.113883.10.20.24.2.2"/>
					
					<templateId root="2.16.840.1.113883.10.20.27.2.1" extension="2017-06-01"/>
					
					<templateId root="2.16.840.1.113883.10.20.27.2.3" extension="2017-07-01"/>
					<code code="55186-1" codeSystem="2.16.840.1.113883.6.1" displayName="measure section"/>
					<title>Measure Section</title>
					<text/>
					
					<entry typeCode="DRIV">
						<act classCode="ACT" moodCode="EVN">
							
							<templateId root="2.16.840.1.113883.10.20.17.3.8"/>
							<id root="3d7c11cf-b01b-4527-a704-c098c162779d"/>
							<code code="252116004" codeSystem="2.16.840.1.113883.6.96" displayName="Observation Parameters"/>
							<effectiveTime>
								<low value="20170101"/>
								<high value="20171231"/>
							</effectiveTime>
						</act>
					</entry>
					<entry>
						<organizer classCode="CLUSTER" moodCode="EVN">
							
							<templateId root="2.16.840.1.113883.10.20.24.3.98"/>
							
							<templateId root="2.16.840.1.113883.10.20.27.3.1" extension="2016-09-01"/>
							
							<templateId root="2.16.840.1.113883.10.20.27.3.17" extension="2016-11-01"/>
							<id root="40280381-51F0-825B-0152-22A639D81762"/>
							<statusCode code="completed"/>
							
							<reference typeCode="REFR">
								<externalDocument classCode="DOC" moodCode="EVN">
									<id root="2.16.840.1.113883.4.738" extension="40280381-51F0-825B-0152-22A639D81762"/>
									<code code="57024-2" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Health Quality Measure Document"/>
									<text>ADHD: Follow-Up Care for Children Prescribed Attention-Deficit/Hyperactivity Disorder (ADHD) Medication</text>
								</externalDocument>
							</reference>
							<component>
								<observation classCode="OBS" moodCode="EVN">
									<templateId root="2.16.840.1.113883.10.20.27.3.5" extension="2016-09-01" />
									<templateId root="2.16.840.1.113883.10.20.27.3.16" extension="2016-11-01" />
									<code code="ASSERTION" codeSystem="2.16.840.1.113883.5.4" codeSystemName="ActCode" displayName="Assertion" />
									<statusCode code="completed" />
									<value xsi:type="CD" code="IPOP" codeSystem="2.16.840.1.113883.5.4" codeSystemName="ActCode"/>
									
									<entryRelationship typeCode="SUBJ" inversionInd="true">
										<observation classCode="OBS" moodCode="EVN">
											<templateId root="2.16.840.1.113883.10.20.27.3.3" />
											<templateId root="2.16.840.1.113883.10.20.27.3.24" />
											<code code="MSRAGG" codeSystem="2.16.840.1.113883.5.4" codeSystemName="ActCode" displayName="rate aggregation" />
											<statusCode code="completed" />
											<value xsi:type="INT" value="1" />
											<methodCode code="COUNT" codeSystem="2.16.840.1.113883.5.84" codeSystemName="ObservationMethod" displayName="Count" />
										</observation>
									</entryRelationship>
									
									
									<reference typeCode="REFR">
										<externalObservation classCode="OBS" moodCode="EVN">
											<id root="4DF80BC3-980B-465E-8591-616C7DB74FBD" />
										</externalObservation>
									</reference>
								</observation>
							</component>
						</organizer>
					</entry>
				</section>
			</component>
		</structuredBody>
	</component>
</ClinicalDocument>`

**Comment by sfradkin** [comment] 2018-03-14 21:55
@chacliff: Thanks for bringing this to our attention.  We'll take a look at this and we will let you know if a full file will be helpful.

**Comment by chacliff** [comment] 2018-03-14 22:14
awesome thanks, i look forward to hearing back, i'm stumped as to the reason this is failing.

**Comment by halprin** [comment] 2018-03-15 21:21
Hey there @chacliff.  I spliced the quality section you provided above into a valid QRDA3 file, but I cannot reproduce your error.  I got other errors, but I presume that was due to the fact that you decided not to share the other denominator, numerator, and denom exclusion parts.  I even tried earlier versions of our converter and still couldn't produce an error 52.  This is indeed puzzling.  Would you be able to share a non-PII (change the TIN and NPI) version of the QRDA3 file?  Thanks!

**Comment by chacliff** [comment] 2018-03-20 15:46
Hi, 
After literally copy pasting using one of your  sample files i was able to rule down the problem to the inner entry relationships. Basically the "stratum" entry relationship were missing templateIds. Also all the entry relationships have 2 templateId and only one was being generated. 

In an attempt to help this product improve, i believe it would be better if you guys could change your error messages a bit. In the outlined error below it looks you are indicating the entry location as an array [ ]. Unfortunately your error output did not go deep enough though. it stopped at the top level "observation," it would of been helpful to either receive a line number or at the very least an indication that the error was describing an issue with an internal "entryRelationship" segment.  Another step further would be to list that a templateId is completely missing as part of a validation error. 

I hope this is helpful!

{ "errorCode" : 52, "message" : "CT - Measure data must have exactly one Aggregate Count.", "path" : "/*[local-name() = 'ClinicalDocument' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'structuredBody' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3'][1]/*[local-name() = 'section' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'entry' and namespace-uri() = 'urn:hl7-org:v3'][2]/*[local-name() = 'organizer' and namespace-uri() = 'urn:hl7-org:v3']/*[local-name() = 'component' and namespace-uri() = 'urn:hl7-org:v3'][1]/*[local-name() = 'observation' and namespace-uri() = 'urn:hl7-org:v3']" }

**Comment by sfradkin** [comment] 2018-03-20 17:08
@chacliff: Thanks for the feedback.  We're actually in the process of re-evaluating all of our validations and error messages right now, so we'll incorporate your feedback into that process.

I'm going to go ahead and close this issue by the end of today unless you feel that there's reason to keep it open longer.

**Comment by chacliff** [comment] 2018-03-20 17:35
yeah i'm good so you can close it whenever you are ready. i'll re-open it if it a customer gets back to me and its not fixed for some reason.

**Closed** 2018-03-20 20:21 UTC
Labels: evaluating
